# Hooks that run after HEAD changes or a file is explicitly checked out. Useful
# for updating source tags (e.g. via ctags) or warning about new migrations,
# etc.
PostCheckout:
  IndexTags:
    enabled: false

# Hooks that are run after `git commit` is executed, before the commit message
# editor is displayed. These hooks are ideal for syntax checkers, linters, and
# other checks that you want to run before you allow a commit object to be
# created.
PreCommit:
  # disable haml-lint for now since it complains about things but has no way to disable said complaints
  HamlLint:
    enabled: false

  Jscs:
    enabled: false

  JsHint:
    description: 'Analyzing with JSHint'
    include: '**/*.js'

  PythonFlake8:
    enabled: false

  TravisLint:
    enabled: false

# Hooks that are run against every commit message after a user has written it.
# These hooks are useful for enforcing policies on commit messages written for a
# project.
CommitMsg:
  ALL:
    enabled: false