# Hooks that run after HEAD changes or a file is explicitly checked out. Useful
# for updating source tags (e.g. via ctags) or warning about new migrations,
# etc.
PostCheckout:
  ALL:
    required: false
    quiet: false
  BundleCheck:
    description: 'Checking Gemfile dependencies'
    include:
      - 'Gemfile'
      - 'Gemfile.lock'
      - '*.gemspec'
  IndexTags:
    enabled: false
