# list of the tables and columns that should have multiple languages generated
tables:
  events:
    - title
    - location

  pages:
    - title
    - seo_title
    - seo_keywords
    - seo_description

  posts:
    - title
    - excerpt
    - seo_title
    - seo_keywords
    - seo_description